import { CLIENT_ROUTES } from '@/api/routes';
import { QUERY_KEYS } from '@/constants';
import { FIRST_PAGE, PAGE_OFFSET } from '@/constants/view';
import Layout from '@/layout/layout';
import { saveDetails, setCardsList, setLoading } from '@/store/features';
import { wrapper } from '@/store/store';
import { ServerCookieManager } from '@/utils/server-cookie-manager';
import { GetServerSidePropsContext, InferGetServerSidePropsType } from 'next';
import Head from 'next/head';
import { ParsedUrlQuery } from 'node:querystring';

export interface SpacecraftParams extends ParsedUrlQuery {
  spacecraftId?: string;
}

export const getServerSideProps = wrapper.getServerSideProps(
  (store) => async (context: GetServerSidePropsContext<SpacecraftParams>) => {
    const theme = ServerCookieManager.getTheme(context);
    const { name = '', page } = context.query;
    const nextPage = page ? Number(page) : FIRST_PAGE;
    const protocol = context.req.headers.host?.includes('localhost')
      ? 'http'
      : 'https';
    const baseUrl = `${protocol}://${context.req.headers.host}`;
    const urlCards = `${baseUrl}/${CLIENT_ROUTES.CARDS}?${QUERY_KEYS.NAME}=${name}&${QUERY_KEYS.PAGE}=${nextPage - PAGE_OFFSET}`;
    const cards = await fetch(urlCards).then((res) => res.json());
    const spacecraftId = context.params?.spacecraftId;

    if (spacecraftId) {
      const urlCardDetails = `${baseUrl}/${CLIENT_ROUTES.CARD_DETAILS(spacecraftId)}`;
      const cardDetails = await fetch(urlCardDetails).then((res) => res.json());

      store.dispatch(saveDetails(cardDetails.spacecraft));
      console.log('cardDetails: ', cardDetails);
    }

    store.dispatch(setCardsList(cards));
    store.dispatch(setLoading(false));

    return {
      props: {
        theme,
      },
    };
  }
);

export type HomeProps = InferGetServerSidePropsType<typeof getServerSideProps>;

export default function Page() {
  return (
    <>
      <Head>
        <title>Star Trek</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" type="image/png" href="/favicon-32x32.png" />
      </Head>
      <Layout />
    </>
  );
}
