import { CLIENT_ROUTES } from '@/api/routes';
import { SpacecraftsResponse } from '@/api/types';
import { QUERY_KEYS } from '@/constants';
import { FIRST_PAGE, PAGE_OFFSET } from '@/constants/view';
import Layout from '@/layout/layout';
import { ServerCookieManager } from '@/utils/server-cookie-manager';
import { GetServerSidePropsContext } from 'next';
import Head from 'next/head';

/**
 * Fetches server-side props for the page.
 *
 * @param context - The context object containing request information.
 * @returns An object containing the theme and cards data as props.
 */
export const getServerSideProps = async (
  context: GetServerSidePropsContext
) => {
  const theme = ServerCookieManager.getTheme(context);
  const firstPage = (FIRST_PAGE - PAGE_OFFSET).toString();

  const { name = '', pageNumber = firstPage } = context.query;
  const protocol = context.req.headers.host?.includes('localhost')
    ? 'http'
    : 'https';
  const baseUrl = `${protocol}://${context.req.headers.host}`;
  const url = `${baseUrl}/${CLIENT_ROUTES.CARDS}?${QUERY_KEYS.NAME}=${name}&${QUERY_KEYS.PAGE}=${pageNumber}`;
  const response = await fetch(url);
  const cards: SpacecraftsResponse = await response.json();

  return { props: { theme, cards } };
};

export type HomeProps = Awaited<ReturnType<typeof getServerSideProps>>['props'];

export default function Home() {
  return (
    <>
      <Head>
        <title>Star Trek</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" type="image/png" href="/favicon-32x32.png" />
      </Head>
      <Layout />
    </>
  );
}
